name: Release

on:
  release:
    types: [created]

jobs:
  release:
    name: release-${{ matrix.target }}
    runs-on: windows-latest
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        target: [
          i686-pc-windows-msvc,
          x86_64-pc-windows-msvc,
        ]
        archive: zip

    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}